"""统一 TTS 入口。"""

from .client import Client, Speaker
from .errors import (
    ConfigurationError,
    NoDefaultSpeakerError,
    ProviderError,
    SpeakerNotFoundError,
    VoiceHubError,
)
from .interfaces import TTSEngine
from .providers import (
    MINIMAX_BASE_URL,
    MINIMAX_SYSTEM_VOICE_BY_ID,
    MINIMAX_SYSTEM_VOICE_IDS,
    MINIMAX_SYSTEM_VOICES,
    MINIMAX_SYSTEM_VOICES_BY_LANGUAGE,
    MINIMAX_T2A_MODEL,
    MINIMAX_VOICE_CLONE_MODEL,
    MIMO_BUILTIN_VOICE_BY_ID,
    MIMO_BUILTIN_VOICE_IDS,
    MIMO_BUILTIN_VOICES,
    AzureTTS,
    MimoTTS,
    MimoVoice,
    MimoVoiceSpec,
    MinimaxClonePrompt,
    MinimaxTTS,
    MinimaxVoice,
    MinimaxVoiceClone,
    MinimaxVoiceCloneTTS,
    MinimaxVoiceCloneResult,
    MinimaxVoiceSpec,
    OpenAITTS,
)
from .sample import VoiceSample
from .speech import Speech

__all__ = [
    "AzureTTS",
    "Client",
    "ConfigurationError",
    "MINIMAX_BASE_URL",
    "MINIMAX_SYSTEM_VOICE_BY_ID",
    "MINIMAX_SYSTEM_VOICE_IDS",
    "MINIMAX_SYSTEM_VOICES",
    "MINIMAX_SYSTEM_VOICES_BY_LANGUAGE",
    "MINIMAX_T2A_MODEL",
    "MINIMAX_VOICE_CLONE_MODEL",
    "MIMO_BUILTIN_VOICE_BY_ID",
    "MIMO_BUILTIN_VOICE_IDS",
    "MIMO_BUILTIN_VOICES",
    "MimoTTS",
    "MimoVoice",
    "MimoVoiceSpec",
    "MinimaxClonePrompt",
    "MinimaxTTS",
    "MinimaxVoice",
    "MinimaxVoiceClone",
    "MinimaxVoiceCloneTTS",
    "MinimaxVoiceCloneResult",
    "MinimaxVoiceSpec",
    "NoDefaultSpeakerError",
    "OpenAITTS",
    "ProviderError",
    "Speaker",
    "SpeakerNotFoundError",
    "Speech",
    "TTSEngine",
    "VoiceHubError",
    "VoiceSample",
]
